### ISSUE TITLE
Receiver hashring config has only a single hashring

### ISSUE THREAD

**Issue by philipgough** [thanos-community/thanos-operator#172]
When deploying the sample manifests, [for receiver](https://github.com/thanos-community/thanos-operator/blob/main/config/samples/v1alpha1_thanosreceive.yaml), despite two hashrings being present, the configmap only contains a single entry

```yaml
apiVersion: v1
data:
  hashrings.json: |-
    [
        {
            "hashring": "green",
            "tenant_matcher_type": "exact",
            "endpoints": [
                {
                    "address": "thanos-receive-ingester-example-receive-green-0.thanos-receive-ingester-example-receive-green.thanos-operator-system.svc.cluster.local:10901",
                    "az": ""
                }
            ]
        }
    ]
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-20T11:35:14Z"
  labels:
    app.kubernetes.io/component: thanos-receive-router
    app.kubernetes.io/instance: thanos-receive-router-example-receive
    app.kubernetes.io/managed-by: thanos-operator
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/part-of: thanos
    operator.thanos.io/owner: example-receive
  name: thanos-receive-router-example-receive
  namespace: thanos-operator-system
  ownerReferences:
  - apiVersion: monitoring.thanos.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ThanosReceive
    name: example-receive
    uid: a06cb766-168d-4a8f-8131-e2b94c3389dc
```
